create table public.products (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  name text not null,
  description text null,
  deleted_at timestamp with time zone null,
  recommended_price numeric null,
  user_id uuid null default auth.uid (),
  deleted_by uuid null default auth.uid (),
  active boolean not null default true,
  constraint products_pkey primary key (id)
) TABLESPACE pg_default;

create table public.stores (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  name text not null,
  street text null,
  city text null,
  zip_code text null,
  phone_number text null,
  timezone text null,
  active boolean not null default true,
  deleted_by uuid null default auth.uid (),
  user_id uuid not null default auth.uid (),
  deleted_at timestamp with time zone null,
  constraint stores_pkey primary key (id)
) TABLESPACE pg_default;

create table public.stores_products (
  id bigint generated by default as identity not null,
  store_id uuid null default gen_random_uuid (),
  product_id uuid null default gen_random_uuid (),
  price numeric not null,
  availability boolean null default true,
  constraint stores_products_pkey primary key (id),
  constraint stores_products_product_id_fkey foreign KEY (product_id) references products (id),
  constraint stores_products_store_id_fkey foreign KEY (store_id) references stores (id)
) TABLESPACE pg_default;